import ExcelJS from "exceljs";
import type { BomLine } from "../models";

const ESTIMATE_COLUMNS = [
  { header: "Service category", key: "category", width: 22 },
  { header: "Service name", key: "service", width: 28 },
  { header: "Type", key: "type", width: 26 },
  { header: "Custom name", key: "custom", width: 28 },
  { header: "Region", key: "region", width: 16 },
  { header: "Description", key: "description", width: 48 },
  { header: "Estimated upfront cost", key: "upfront", width: 20 },
  { header: "Estimated monthly cost", key: "monthly", width: 22 },
];

const ASSUMPTION_COLUMNS = [
  { header: "Service category", key: "category", width: 22 },
  { header: "Service name", key: "service", width: 28 },
  { header: "Type", key: "type", width: 22 },
  { header: "Custom name", key: "custom", width: 28 },
  { header: "Resource", key: "resource", width: 44 },
  { header: "Assumption", key: "assumption", width: 90 },
  { header: "Unit price", key: "unitPrice", width: 14 },
  { header: "Quantity", key: "quantity", width: 14 },
  { header: "Unit", key: "unit", width: 16 },
  { header: "Monthly cost", key: "monthly", width: 18 },
];

export async function buildExcelBom(
  lines: BomLine[],
  region: string,
  currency: string,
  appName: string,
  globalAssumptions: string[],
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "azure-cost-assessment";
  wb.created = new Date();

  // ----- Estimate sheet -----
  const est = wb.addWorksheet("Estimate");
  const total = lines.reduce((sum, l) => sum + l.monthlyCost, 0);

  est.addRows([
    ["Field", "Value"],
    ["Estimate generated by", "azure-cost-assessment"],
    ["Generated at", new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC"],
    ["Application / workload", appName || "(not set)"],
    ["Billing region", region],
    ["Currency", currency],
    ["Billing frequency", "Monthly"],
    ["Total estimated monthly cost", Math.round(total * 100) / 100],
  ]);
  est.getRow(1).font = { bold: true };

  const headerRowIdx = 11;
  est.getRow(headerRowIdx).values = ESTIMATE_COLUMNS.map((c) => c.header);
  est.getRow(headerRowIdx).font = { bold: true };
  ESTIMATE_COLUMNS.forEach((c, i) => {
    est.getColumn(i + 1).width = c.width;
  });

  for (const l of lines) {
    est.addRow([
      l.category,
      l.serviceName || l.category,
      l.sku || l.meter,
      l.customName,
      l.region,
      l.resource,
      0,
      Math.round(l.monthlyCost * 100) / 100,
    ]);
  }

  // ----- Cost Assumptions sheet -----
  const assump = wb.addWorksheet("Cost Assumptions");
  const sectionRow = assump.addRow(["Section"]);
  sectionRow.font = { bold: true };
  assump.addRow(["Assessment-wide assumptions"]);
  assump.addRow(["#", "Assumption"]);
  assump.getRow(3).font = { bold: true };
  const globals = globalAssumptions.length > 0 ? globalAssumptions : ["(none)"];
  globals.forEach((g, i) => assump.addRow([i + 1, g]));

  assump.addRow([]);
  assump.addRow(["Per-line assumptions"]).font = { bold: true };
  assump.addRow(ASSUMPTION_COLUMNS.map((c) => c.header));
  assump.getRow(assump.rowCount).font = { bold: true };
  ASSUMPTION_COLUMNS.forEach((c, i) => {
    assump.getColumn(i + 1).width = c.width;
  });
  for (const l of lines) {
    assump.addRow([
      l.category,
      l.serviceName || l.category,
      l.sku || l.meter,
      l.customName,
      l.resource,
      l.assumption,
      l.unitPrice,
      l.quantity,
      l.unit,
      Math.round(l.monthlyCost * 100) / 100,
    ]);
  }

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
